### ISSUE TITLE
Fast User Switching does not work with macOS Big Sur

### ISSUE THREAD

**Issue by nicokosi** [aiyodk/Alfred-Extensions#23]
Since I have upgraded to macOS Big Sur, "Fast User Switching" does not work anymore:
![EtEcQuVXEAI8rbd](https://user-images.githubusercontent.com/3862051/106395027-41b39d80-6400-11eb-9218-c7582275d209.jpeg)

If I understand correctly, Apple does not provide `User.menu` script anymore, see related issue: https://apple.stackexchange.com/questions/409820/access-fast-user-switching-from-a-script-in-big-sur

**Comment by aiyodk** [comment]
Apple have removed CGSession in macOS Big Sur and there is, to my knowledge, no other way to activate Fast User Switching with scripting.
