### ISSUE TITLE
Breaks with Virtual Box 5.0

### ISSUE THREAD

**Issue by dirq** [aiyodk/Alfred-Extensions#9]
I just installed virtual box 5.0 and the alfred workflow doesn't work anymore.  I didn't realize how often I used your workflow until it broke.  Thanks for all the good times.  Hopefully you still work on this project and can submit a fix when you get time.  Thanks.

**Comment by aiyodk** [comment]
Hi Dirk,

You are right, my workflow stopped working after installing Virtualbox 5.0.

It seems that VBoxManage (the command line tool shipped with VirtualBox) has been moved from /usr/bin to /usr/local/bin and thus is no longer in Alfred.app’s Bash $PATH.

The workflow I am sending to you here should work fine, but I have not tested it on a machine with Virtualbox 4.xx - once I am sure it works with both Virtualbox 4.xx and 5.0 I will make it available to everyone.

Thanks for you mail!

Cheers  
Jonas

**Comment by dirq** [comment]
Did you push a new branch up for this or should I change the path somewhere?  Thanks for the insanely quick reply! :)

**Comment by stffndtz** [comment]
Is there any progress on this? I hate starting VBox before getting to my VM.

Thanks in advance!

**Comment by jasonkarns** [comment]
could this get pushed as a branch, at least, until it's verified with virtualbox 4.0?

**Comment by aiyodk** [comment]
I finally added support for VirtualBox 5.x, sorry for the long wait.
